import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/index.module.css'
import Copyright from '../components/copyright';
import Typewriter from 'typewriter-effect';
import Link from 'next/link'
import Github from '../public/github.svg';
import LinkedIn from '../public/linkedin.svg';
import YouTube from '../public/youtube.svg';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Julian Aßmann</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hi there, I'm Julian.</h1>
        <div className={styles.typewriterContainer}>
          <h2 className={styles.typewriterText}>
            <Typewriter
              options={{
                strings: [
                  'Master Student of Computer Science @ SAP', 
                  'Open Source Developer',
                  'YouTuber (Programming Tutorials)'
                ],
                autoStart: true,
                loop: true,
                delay: 50,
                deleteSpeed: 20,
              }}
            />
          </h2>
        </div>
        <h3>Find me on</h3>
        <div className={styles.externalLogosContainer}>
          <Link href="https://github.com/JulianAssmann">
            <a><Github width={50} height={50} fill="white" /></a>
          </Link>
          <Link href="https://www.linkedin.com/in/julian-a%C3%9Fmann-195798156/">
            <a><LinkedIn width={50} height={50} fill="white" /></a>
          </Link>
          <Link href="https://www.youtube.com/channel/UCPOv6aROWBSxBNXXTDIHf2w">
            <a><YouTube width={50} height={50} fill="white" /></a>
          </Link>
        </div>
      </main>

      <footer>
        <Copyright />
      </footer>
    </div>
  )
}

export default Home
